apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: classmere-api
  labels:
    app: classmere
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classmere
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: classmere
        tier: api
    spec:
      containers:
      - image: gcr.io/classmere-183817/github-classmere-api:28f044e91e4dec9b91933f2d97b17bc1b4f990cb
        name: api
        env:
        - name: MONGO_URL
          value: "mongodb://classmere-mongo:27017/test"
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
          name: api
