apiVersion: v1
kind: Service
metadata:
  name: classmere-mongo
  labels:
    name: classmere-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: classmere
    tier: mongo
