apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: classmere-mongo
  labels:
    app: classmere
    name: classmere-mongo
spec:
  selector:
    matchLabels:
      app: classmere
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: classmere
        tier: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          hostPort: 27017
          name: classmere-mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
